export const trendingMovies = [
  {
    id: 1,
    title: "Galactic Quest , Galactic Quest , Galactic Quest",
    releaseYear: 2024,
    genre: "Sci-Fi",
    rating: 8.3,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "An epic journey through the stars to save the galaxy from an ancient evil. Captain Lira and her crew must navigate treacherous wormholes, alien civilizations, and political sabotage to prevent a doomsday device from awakening. With breathtaking visuals and a powerful score, Galactic Quest redefines the space opera genre for a new generation.",
  },
  {
    id: 2,
    title: "Lost in Tokyo",
    releaseYear: 2023,
    genre: "Drama",
    rating: 7.5,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "A heartfelt story of self-discovery and new beginnings in the bustling city of Tokyo. After a sudden breakup, American photographer Claire travels to Japan, where she finds inspiration, unexpected friendships, and a deeper understanding of her own identity. Visually stunning and emotionally resonant, this drama explores the beauty of solitude and the courage to start over.",
  },
  {
    id: 3,
    title: "Mystery Manor",
    releaseYear: 2025,
    genre: "Thriller",
    rating: 8.0,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "A group of strangers trapped in a mansion uncover dark secrets and unexpected twists. When an eccentric billionaire invites eight guests to his remote estate, a murder sets off a chain of terrifying revelations. With each character hiding their past, survival depends on solving the mystery before the killer strikes again. A chilling homage to classic whodunits with a modern psychological twist.",
  },
  {
    id: 4,
    title: "The Last Melody",
    releaseYear: 2024,
    genre: "Romance",
    rating: 7.8,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "A touching tale of love, loss, and music that brings two souls together. Pianist Leo, grieving the loss of his wife, finds solace in teaching a gifted but troubled student named Hana. As music rekindles their spirits, they face old wounds and new challenges in a story that shows how art can heal even the deepest scars. Poignant performances and a haunting soundtrack make this a must-watch romance.",
  },
  {
    id: 5,
    title: "Mystery Manor",
    releaseYear: 2025,
    genre: "Thriller",
    rating: 8.0,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "A group of strangers trapped in a mansion uncover dark secrets and unexpected twists. The old house holds more than just creaky floors—it conceals a history of betrayal, greed, and revenge. As storm clouds gather outside, tensions rise inside, and survival becomes a game of intellect and instinct. A suspenseful ride from start to finish.",
  },
  {
    id: 6,
    title: "The Last Melody",
    releaseYear: 2024,
    genre: "Romance",
    rating: 7.8,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "A touching tale of love, loss, and music that brings two souls together. As Leo and Hana bond over their shared passion for piano, their friendship slowly blossoms into something deeper. But the shadow of past heartbreak threatens to undo what they’ve built. A beautiful film that reminds us of the timeless power of music and emotional connection.",
  },
  {
    id: 7,
    title: "Mystery Manor",
    releaseYear: 2025,
    genre: "Thriller",
    rating: 8.0,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "A group of strangers trapped in a mansion uncover dark secrets and unexpected twists. With the power out and communication lost, fear grips the group as they realize the killer might be among them. The house becomes a psychological battlefield as trust breaks down and clues lead to shocking revelations.",
  },
  {
    id: 8,
    title: "The Last Melody",
    releaseYear: 2024,
    genre: "Romance",
    rating: 7.8,
    posterUrl: "https://i0.wp.com/joshatthemovies.com/wp-content/uploads/2021/06/Poser-QP.jpeg?fit=800%2C1200&ssl=1",
    description: "A touching tale of love, loss, and music that brings two souls together. Set against the backdrop of a small European town, the film explores the redemptive journey of two artists brought together by fate and melody. A deeply emotional narrative that explores grief, passion, and the courage to love again.",
  },
];
